package org.example.model;

public enum IssueName {
    // Internal Issues
    VALIDATION_ISSUE,
    AUTHENTICATION_ISSUE,
    RESOURCE_ISSUE,
    DATA_INTEGRITY_ISSUE,
    CONCURRENCY_ISSUE,
    CONFIGURATION_ISSUE,
    EXECUTION_ISSUE,
    PERFORMANCE_ISSUE,

    // Dependency Issues
    SERVICE_ISSUE,
    SERVICE_TIMEOUT,
    LIBRARY_ISSUE,
    DATABASE_ISSUE,
    INFRASTRUCTURE_ISSUE,
    COMMUNICATION_ISSUE,
    VERSION_COMPATIBILITY_ISSUE
}
